version: 0.1.0.{build}
branches:
  only:
    - main
    - appveyor
image:
  - Ubuntu
  - Visual Studio 2017
build_script:
  - ps: .\build.ps1 -IsOfficialBuild
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
os: Visual Studio 2017
artifacts:
  - path: 'artifacts\*.nupkg'
    name: Packages
    type: NuGetPackages
deploy:
  - provider: GitHub
    description: 'See https://github.com/natemcmaster/xunit-extensions/blob/master/CHANGELOG.md for details'
    auth_token:
      secure: 7gza5cyC0Fwp5LcFPz9dGMcHXP2jxbrnu7er9R/HkdvnhzGJVADvOtfYO7+Vow5p
    artifact: Packages
    draft: false
    prerelease: true
    on:
      branch: main                 # release from main branch only
      appveyor_repo_tag: true      # deploy on tag push only
